apiVersion: apps/v1
kind: Deployment
metadata:
  name: itdt
  labels:
    app: itdt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: itdt-frontend
  template:
    metadata:
      labels:
        app: itdt-frontend
    spec:
      containers:
      - name: itdt-frontend
        image: ifilyaninitmo/itdt-contained-frontend:master
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_USERNAME
          value: Dandor
        - name: REACT_APP_COMPANY_NAME
          value: ITMO
